mutation createUser($email: String!, $password: String!) {
  insert_users_one(object: { email: $email, password: $password }) {
    email
    id
  }
}

query getUserData($email: String!) {
  users(where: { email: { _eq: $email } }) {
    email
    id
    password
  }
}
